export type Veiculo = {
    id: number;
    marca: string;
    modelo: string;
    grupo: string;
    ano: number;
    cor: string;
    valorDiaria: number;
    quilometragem: number;
    statusVeiculo: string;
    placa: string;
    estoqueId: number;
};

const Veiculos: Veiculo[] = [
    {
        id: 1,
        marca: "Toyota",
        modelo: "Corolla",
        grupo: "A",
        ano: 2022,
        cor: "AZUL",
        valorDiaria: 199.9,
        quilometragem: 34800,
        statusVeiculo: "DISPONIVEL",
        placa: "ABC-1234",
        estoqueId: 1,
    },
    {
        id: 2,
        marca: "Honda",
        modelo: "Civic",
        grupo: "A",
        ano: 2021,
        cor: "PRATA",
        valorDiaria: 189.9,
        quilometragem: 40200,
        statusVeiculo: "DISPONIVEL",
        placa: "DEF-5678",
        estoqueId: 1,
    },
    {
        id: 3,
        marca: "Volkswagen",
        modelo: "Golf",
        grupo: "B",
        ano: 2020,
        cor: "VERMELHO",
        valorDiaria: 209.9,
        quilometragem: 51000,
        statusVeiculo: "MANUTENCAO",
        placa: "GHI-9012",
        estoqueId: 2,
    },
    {
        id: 4,
        marca: "Ford",
        modelo: "Ka",
        grupo: "C",
        ano: 2019,
        cor: "BRANCO",
        valorDiaria: 149.9,
        quilometragem: 65500,
        statusVeiculo: "DISPONIVEL",
        placa: "JKL-3456",
        estoqueId: 2,
    },
    {
        id: 5,
        marca: "Chevrolet",
        modelo: "Onix",
        grupo: "C",
        ano: 2023,
        cor: "PRETO",
        valorDiaria: 169.9,
        quilometragem: 12500,
        statusVeiculo: "DISPONIVEL",
        placa: "MNO-7890",
        estoqueId: 3,
    },
    {
        id: 6,
        marca: "Fiat",
        modelo: "Argo",
        grupo: "C",
        ano: 2022,
        cor: "CINZA",
        valorDiaria: 159.9,
        quilometragem: 23400,
        statusVeiculo: "LOCADO",
        placa: "PQR-1235",
        estoqueId: 3,
    },
    {
        id: 7,
        marca: "Hyundai",
        modelo: "HB20",
        grupo: "B",
        ano: 2021,
        cor: "AZUL",
        valorDiaria: 179.9,
        quilometragem: 30100,
        statusVeiculo: "DISPONIVEL",
        placa: "STU-5679",
        estoqueId: 4,
    },
    {
        id: 8,
        marca: "Renault",
        modelo: "Kwid",
        grupo: "D",
        ano: 2020,
        cor: "VERDE",
        valorDiaria: 139.9,
        quilometragem: 48000,
        statusVeiculo: "DISPONIVEL",
        placa: "VWX-9013",
        estoqueId: 4,
    },
    {
        id: 9,
        marca: "Peugeot",
        modelo: "208",
        grupo: "B",
        ano: 2021,
        cor: "BRANCO",
        valorDiaria: 189.9,
        quilometragem: 29500,
        statusVeiculo: "MANUTENCAO",
        placa: "YZA-3457",
        estoqueId: 5,
    },
    {
        id: 10,
        marca: "Nissan",
        modelo: "Versa",
        grupo: "A",
        ano: 2023,
        cor: "PRATA",
        valorDiaria: 199.9,
        quilometragem: 9600,
        statusVeiculo: "DISPONIVEL",
        placa: "BCD-7891",
        estoqueId: 5,
    },
    {
        id: 11,
        marca: "Kia",
        modelo: "Cerato",
        grupo: "A",
        ano: 2022,
        cor: "PRETO",
        valorDiaria: 209.9,
        quilometragem: 28000,
        statusVeiculo: "LOCADO",
        placa: "EFG-1236",
        estoqueId: 1,
    },
    {
        id: 12,
        marca: "Mitsubishi",
        modelo: "Lancer",
        grupo: "B",
        ano: 2020,
        cor: "CINZA",
        valorDiaria: 199.0,
        quilometragem: 49000,
        statusVeiculo: "DISPONIVEL",
        placa: "HIJ-5670",
        estoqueId: 1,
    },
    {
        id: 13,
        marca: "Toyota",
        modelo: "Yaris",
        grupo: "C",
        ano: 2021,
        cor: "AZUL",
        valorDiaria: 169.9,
        quilometragem: 31500,
        statusVeiculo: "DISPONIVEL",
        placa: "KLM-9014",
        estoqueId: 2,
    },
    {
        id: 14,
        marca: "Ford",
        modelo: "Fusion",
        grupo: "A",
        ano: 2019,
        cor: "BRANCO",
        valorDiaria: 219.9,
        quilometragem: 72000,
        statusVeiculo: "MANUTENCAO",
        placa: "NOP-3458",
        estoqueId: 2,
    },
    {
        id: 15,
        marca: "Chevrolet",
        modelo: "Cruze",
        grupo: "B",
        ano: 2023,
        cor: "VERMELHO",
        valorDiaria: 209.9,
        quilometragem: 15800,
        statusVeiculo: "DISPONIVEL",
        placa: "QRS-7892",
        estoqueId: 3,
    },
    {
        id: 16,
        marca: "Fiat",
        modelo: "Mobi",
        grupo: "D",
        ano: 2021,
        cor: "PRATA",
        valorDiaria: 129.9,
        quilometragem: 36800,
        statusVeiculo: "LOCADO",
        placa: "TUV-1237",
        estoqueId: 3,
    },
    {
        id: 17,
        marca: "Renault",
        modelo: "Logan",
        grupo: "C",
        ano: 2020,
        cor: "AZUL",
        valorDiaria: 159.9,
        quilometragem: 45700,
        statusVeiculo: "DISPONIVEL",
        placa: "WXY-5671",
        estoqueId: 4,
    },
    {
        id: 18,
        marca: "Hyundai",
        modelo: "Creta",
        grupo: "B",
        ano: 2022,
        cor: "CINZA",
        valorDiaria: 219.9,
        quilometragem: 21000,
        statusVeiculo: "DISPONIVEL",
        placa: "ZAB-9015",
        estoqueId: 4,
    },
    {
        id: 19,
        marca: "Peugeot",
        modelo: "2008",
        grupo: "A",
        ano: 2021,
        cor: "PRETO",
        valorDiaria: 229.9,
        quilometragem: 38900,
        statusVeiculo: "DISPONIVEL",
        placa: "CDE-3459",
        estoqueId: 5,
    },
    {
        id: 20,
        marca: "Nissan",
        modelo: "Kicks",
        grupo: "B",
        ano: 2023,
        cor: "BRANCO",
        valorDiaria: 219.9,
        quilometragem: 13400,
        statusVeiculo: "LOCADO",
        placa: "FGH-7893",
        estoqueId: 5,
    },
];

export const getVeiculos = (): Promise<Veiculo[]> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(Veiculos);
        }, 1000); // Simula 1 segundo de delay
    });
};
